### ISSUE TITLE
Switching the camera off also stops screensharing

### ISSUE THREAD

**Issue by emembrives** [garage44/pyrite#106]
When both presenting and screensharing, switching the camera off also switches off screensharing. However, screensharing should continue even if the camera is off.

## To Reproduce

1. Create a group with operator privileges
2. Join this group; if necessary, switch on the camera
3. Click "Switch screensharing on" in the right bar, and share something (e.g. another browser tab)
4. Click "Switch camera off"

## Expected behavior

* Expected: The camera view should disappear, leaving only the screensharing view.
* Actual: Both view disappear, then a view showing only the Pyrite logo appears.

## Environment (please complete the following information)

- Device: Lenovo laptop
- OS: Ubuntu 22.04
- Browser: Chrome 104.0.5112.79
- Application version: top of `develop` branch (commit [685a2eb](https://github.com/garage44/pyrite/commit/685a2ebb8241e289a5f062b56bd6fe0136287432))

**Comment by jvanveen** [comment]
Thanks for the clear report. I'll check it out asap

**Comment by jvanveen** [comment]
Commit dec6947e0b79625e9a475964f4016a1e9dc62403 fixes that particular issue, but toggling the other way around (stop screenshare with camera on) also seems buggy. The webcam screen dissappears then. Will check that out later.

**Comment by jvanveen** [comment]
Fixed by @emembrives in 7cf342a6b070b4a4141871eb5b9013e2a5bc8d05
