### ISSUE TITLE
"Group renamed" notification lists the new name twice

### ISSUE THREAD

**Issue by saaska** [garage44/pyrite#127]
# Description

When a group is renamed in the admin interface, the rename message shows `group <newname> renamed to <newname>`

## To Reproduce

1. Go to admin interface
2. Click on 'groups'
3. Click on 'add group' or click on an existing group
4. Change the Group Name field to NewName
5. Click 'Store Group' 
6. A notification appears saying `group NewName renamed to NewName`

## Expected behavior

A notification appears saying `group <OldName> renamed to NewName`

## Screenshots

![image](https://user-images.githubusercontent.com/26275111/200229677-1e19d426-33e1-4ba5-a92b-af9d77dcafa1.png)

## Environment (please complete the following information)

- Macbook pro, MacOS, Chrome 107. Ran `docker-compose up` from the Pyrite repo. 
- Pyrite package.json version, 1.15.0

**Comment by jvanveen** [comment]
Thanks for the report! Nice to see someone is actually using the admin interface :) I'll have a look at it this week.
