### ISSUE TITLE
P2P File sharing

### ISSUE THREAD

**Issue by jvanveen** [garage44/pyrite#13]

**Comment by jech** [comment]
For information, Galene's implementation is here: https://github.com/jech/galene/blob/master/static/galene.js#L2436

**Comment by jvanveen** [comment]
Thanks @jech, this worked almost out-of-the-box. All I still have to do is wire a custom notification component to it. Tracking progress in #81.

**Comment by jech** [comment]
@jvanveen I've amost completely rewritten the file transfer code, and moved most of it into protocol.js.  This should simplify your code quite a bit.  Sorry for not doing it earlier, it would have saved you quite a bit of trouble.

The code now looks like this: https://github.com/jech/galene/blob/master/static/galene.js#L2415
