### ISSUE TITLE
Option to clear credentials?

### ISSUE THREAD

**Issue by DillFrescott** [garage44/pyrite#97]
Love this project! I was just wondering if there was a way to clear the credentials from the input boxes without having to delete the session storage?

**Comment by DillFrescott** [comment]
Perfect! Thank you!

**Comment by jvanveen** [comment]
@DillFrescott This took a while; I had to finish the new settings overlay panel & collapsible presence panel first. I don't have many hours to spend on the project atm. There is now a backspace button next to the login which clears the credentials from the form and the store. Please let me know if it needs more work.

**Comment by DillFrescott** [comment]
Thank you so much!!!!
